_base_: model.py
find_unused_parameters: true
lr_config:
  policy: step
  step:
  - 40
  - 60
  warmup: linear
  warmup_iters: 500
  warmup_ratio: 0.1
restful: False
eval_cache: True
nncf_config:
  compression:
  - algorithm: filter_pruning
    ignored_scopes:
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[cls_convs]/Sequential[0]/NNCFConv2d[0]
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[cls_convs]/Sequential[0]/NNCFConv2d[0]
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[reg_convs]/Sequential[0]/NNCFConv2d[0]
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[reg_convs]/Sequential[0]/NNCFConv2d[0]
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[reg_convs]/Sequential[1]/NNCFConv2d[0]
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[reg_convs]/Sequential[1]/NNCFConv2d[0]
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[cls_convs]/Sequential[1]/NNCFConv2d[0]
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[cls_convs]/Sequential[1]/NNCFConv2d[0]
    params:
      # pruning_init: 0.1
      # pruning_steps: 20
      # pruning_target: 0.3
      schedule: paas_ft
      weight_importance: L1
      prune_downsample_convs: true,
      prune_first_conv: true,
      prune_last_conv: true,
      groupwise_pruning_cfg:
        '0': 0.0
        '1': 0.75
        '2': 0.0
        '3': 0.75
        '4': 0.55
        '5': 0.75
        '6': 0.5
        '7': 0.0
        '8': 0.0
        '9': 0.16666666666666663
        '10': 0.4444444444444444
        '11': 0.875
        '12': 0.29166666666666663
        '13': 0.20833333333333337
        '14': 0.02083333333333337
        '15': 0.0
        '16': 0.39583333333333337
        '17': 0.7083333333333333
        '18': 0.8611111111111112
        '19': 0.9305555555555556
        '20': 0.8472222222222222
        '21': 0.8916666666666666
        '22': 0.6583333333333333
        '23': 0.5083333333333333
        '24': 0.0
        '25': 0.5
        '26': 0.19999999999999996
        '27': 0.0
    # pruning_init: 0.2
  input_info:
    sample_size:
    - 1
    - 3
    - 256
    - 256
  log_dir: .
optimizer:
  lr: 0.05
total_epochs: 80
