_base_: /workspace/nncf/paas/cfg/face-detection-0200/model.py
find_unused_parameters: true
lr_config:
  policy: step
  step:
  - 40
  - 60
  warmup: linear
  warmup_iters: 500
  warmup_ratio: 0.1
restful: True
eval_cache: True
nncf_config:
  compression:
  - algorithm: filter_pruning
    ignored_scopes:
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[cls_convs]/Sequential[0]/NNCFConv2d[0]
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[cls_convs]/Sequential[0]/NNCFConv2d[0]
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[reg_convs]/Sequential[0]/NNCFConv2d[0]
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[reg_convs]/Sequential[0]/NNCFConv2d[0]
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[reg_convs]/Sequential[1]/NNCFConv2d[0]
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[reg_convs]/Sequential[1]/NNCFConv2d[0]
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[cls_convs]/Sequential[1]/NNCFConv2d[0]
    - SingleStageDetector/SSDHead[bbox_head]/ModuleList[cls_convs]/Sequential[1]/NNCFConv2d[0]
    params:
      pruning_init: 0.1
      pruning_steps: 20
      pruning_target: 0.3
      schedule: exponential
      weight_importance: geometric_median
      prune_downsample_convs: true,
      prune_first_conv: true,
      prune_last_conv: true,
    pruning_init: 0.0
  input_info:
    sample_size:
    - 1
    - 3
    - 256
    - 256
  log_dir: .
optimizer:
  lr: 0.05
total_epochs: 80
